//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theNoteTaker_v1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Note
    {
        public int NoteID { get; set; }
        public string Title { get; set; }

        [AllowHtml]
        public string Note1 { get; set; }

        public System.DateTime CreatedOn { get; set; }
    }
}
